/**
 * Shop Items Seed
 * Sprint 7: Populate shop with initial items
 */

import { PrismaClient, ItemType, ItemRarity } from '@prisma/client';

const prisma = new PrismaClient();

const shopItems = [
  // SKINS (common to legendary)
  {
    name: 'Piel Clara',
    description: 'Piel base color claro',
    item_type: 'skin' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/items/skins/skin-light.png',
    icon_url: '/items/skins/icons/skin-light-icon.png',
    preview_url: '/items/skins/preview/skin-light-preview.png',
    price_coins: 100,
    price_gems: null,
    category: 'avatar',
    tags: ['skin', 'avatar', 'base'],
    required_level: 1,
  },
  {
    name: 'Piel Media',
    description: 'Piel base color medio',
    item_type: 'skin' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/items/skins/skin-medium.png',
    icon_url: '/items/skins/icons/skin-medium-icon.png',
    price_coins: 100,
    category: 'avatar',
    tags: ['skin', 'avatar', 'base'],
    required_level: 1,
  },
  {
    name: 'Piel Oscura',
    description: 'Piel base color oscuro',
    item_type: 'skin' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/items/skins/skin-dark.png',
    icon_url: '/items/skins/icons/skin-dark-icon.png',
    price_coins: 100,
    category: 'avatar',
    tags: ['skin', 'avatar', 'base'],
    required_level: 1,
  },
  {
    name: 'Piel Dorada',
    description: 'Piel especial con brillo dorado',
    item_type: 'skin' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/items/skins/skin-golden.png',
    icon_url: '/items/skins/icons/skin-golden-icon.png',
    price_coins: 5000,
    price_gems: 50,
    is_premium: true,
    category: 'avatar',
    tags: ['skin', 'avatar', 'premium', 'golden'],
    required_level: 15,
  },
  {
    name: 'Piel Galaxia',
    description: 'Piel legendaria con efecto de galaxia',
    item_type: 'skin' as ItemType,
    rarity: 'legendary' as ItemRarity,
    image_url: '/items/skins/skin-galaxy.png',
    icon_url: '/items/skins/icons/skin-galaxy-icon.png',
    price_gems: 200,
    is_premium: true,
    category: 'avatar',
    tags: ['skin', 'avatar', 'legendary', 'galaxy'],
    required_level: 30,
  },

  // ACCESSORIES - Hats
  {
    name: 'Gorro Rojo',
    description: 'Gorro deportivo color rojo',
    item_type: 'accessory' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/items/accessories/hat-red.png',
    icon_url: '/items/accessories/icons/hat-red-icon.png',
    price_coins: 250,
    category: 'hats',
    tags: ['accessory', 'hat', 'headwear'],
    required_level: 1,
  },
  {
    name: 'Corona de Oro',
    description: 'Corona real de oro puro',
    item_type: 'accessory' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/items/accessories/crown-gold.png',
    icon_url: '/items/accessories/icons/crown-gold-icon.png',
    price_coins: 3000,
    price_gems: 30,
    category: 'hats',
    tags: ['accessory', 'hat', 'crown', 'premium'],
    required_level: 20,
  },
  {
    name: 'Sombrero de Mago',
    description: 'Sombrero mágico con estrellas',
    item_type: 'accessory' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/items/accessories/wizard-hat.png',
    icon_url: '/items/accessories/icons/wizard-hat-icon.png',
    price_coins: 1500,
    category: 'hats',
    tags: ['accessory', 'hat', 'magic'],
    required_level: 10,
  },

  // ACCESSORIES - Glasses
  {
    name: 'Gafas de Sol',
    description: 'Gafas oscuras estilo moderno',
    item_type: 'accessory' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/items/accessories/sunglasses.png',
    icon_url: '/items/accessories/icons/sunglasses-icon.png',
    price_coins: 500,
    category: 'glasses',
    tags: ['accessory', 'glasses', 'cool'],
    required_level: 5,
  },
  {
    name: 'Gafas Nerd',
    description: 'Gafas de estudio',
    item_type: 'accessory' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/items/accessories/nerd-glasses.png',
    icon_url: '/items/accessories/icons/nerd-glasses-icon.png',
    price_coins: 300,
    category: 'glasses',
    tags: ['accessory', 'glasses', 'nerd'],
    required_level: 1,
  },

  // BADGES - Frames
  {
    name: 'Marco de Bronce',
    description: 'Marco básico de bronce',
    item_type: 'badge' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/frames/bronze-frame.png',
    icon_url: '/frames/icons/bronze-icon.png',
    price_coins: 500,
    category: 'frames',
    tags: ['frame', 'border', 'bronze'],
    required_level: 1,
  },
  {
    name: 'Marco de Plata',
    description: 'Marco elegante de plata',
    item_type: 'badge' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/frames/silver-frame.png',
    icon_url: '/frames/icons/silver-icon.png',
    price_coins: 1000,
    category: 'frames',
    tags: ['frame', 'border', 'silver'],
    required_level: 5,
  },
  {
    name: 'Marco de Oro',
    description: 'Marco premium de oro',
    item_type: 'badge' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/frames/gold-frame.png',
    icon_url: '/frames/icons/gold-icon.png',
    price_coins: 2500,
    price_gems: 25,
    category: 'frames',
    tags: ['frame', 'border', 'gold'],
    required_level: 10,
  },
  {
    name: 'Marco Arcoíris',
    description: 'Marco épico con efecto arcoíris',
    item_type: 'badge' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/frames/rainbow-frame.png',
    icon_url: '/frames/icons/rainbow-icon.png',
    price_gems: 100,
    is_premium: true,
    category: 'frames',
    tags: ['frame', 'border', 'rainbow', 'premium'],
    required_level: 25,
  },
  {
    name: 'Marco Legendario',
    description: 'Marco legendario con animación',
    item_type: 'badge' as ItemType,
    rarity: 'legendary' as ItemRarity,
    image_url: '/frames/legendary-frame.png',
    icon_url: '/frames/icons/legendary-icon.png',
    price_gems: 500,
    is_premium: true,
    is_limited_edition: true,
    stock_limit: 100,
    current_stock: 100,
    category: 'frames',
    tags: ['frame', 'border', 'legendary', 'limited'],
    required_level: 50,
  },

  // EMOTES
  {
    name: 'Emoji Feliz',
    description: 'Emoticono de felicidad',
    item_type: 'emote' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/emotes/happy.png',
    icon_url: '/emotes/icons/happy-icon.png',
    price_coins: 200,
    category: 'emotes',
    tags: ['emote', 'emotion', 'happy'],
    required_level: 1,
  },
  {
    name: 'Emoji Victoria',
    description: 'Emoticono de victoria',
    item_type: 'emote' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/emotes/victory.png',
    icon_url: '/emotes/icons/victory-icon.png',
    price_coins: 400,
    category: 'emotes',
    tags: ['emote', 'emotion', 'victory'],
    required_level: 5,
  },
  {
    name: 'Emoji Fuego',
    description: 'Emoticono de fuego épico',
    item_type: 'emote' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/emotes/fire.png',
    icon_url: '/emotes/icons/fire-icon.png',
    price_coins: 800,
    category: 'emotes',
    tags: ['emote', 'emotion', 'fire', 'epic'],
    required_level: 10,
  },

  // BOOSTS
  {
    name: 'Boost XP x2',
    description: 'Duplica XP ganado por 1 hora',
    item_type: 'boost' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/boosts/xp-2x.png',
    icon_url: '/boosts/icons/xp-2x-icon.png',
    price_coins: 1000,
    category: 'boosts',
    tags: ['boost', 'xp', 'temporary'],
    metadata: { duration_minutes: 60, multiplier: 2, boost_type: 'xp' },
  },
  {
    name: 'Boost Monedas x2',
    description: 'Duplica monedas ganadas por 1 hora',
    item_type: 'boost' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/boosts/coins-2x.png',
    icon_url: '/boosts/icons/coins-2x-icon.png',
    price_gems: 10,
    category: 'boosts',
    tags: ['boost', 'coins', 'temporary'],
    metadata: { duration_minutes: 60, multiplier: 2, boost_type: 'coins' },
  },
  {
    name: 'Mega Boost',
    description: 'Triplica XP y monedas por 30 min',
    item_type: 'boost' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/boosts/mega-boost.png',
    icon_url: '/boosts/icons/mega-boost-icon.png',
    price_gems: 50,
    is_premium: true,
    category: 'boosts',
    tags: ['boost', 'xp', 'coins', 'mega'],
    metadata: { duration_minutes: 30, multiplier: 3, boost_type: 'all' },
  },

  // POWERUPS
  {
    name: 'Escudo Protector',
    description: 'Protege de 1 respuesta incorrecta',
    item_type: 'powerup' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/powerups/shield.png',
    icon_url: '/powerups/icons/shield-icon.png',
    price_coins: 500,
    category: 'powerups',
    tags: ['powerup', 'protection', 'game'],
    metadata: { powerup_type: 'shield', uses: 1 },
  },
  {
    name: '50/50',
    description: 'Elimina 2 respuestas incorrectas',
    item_type: 'powerup' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/powerups/fifty-fifty.png',
    icon_url: '/powerups/icons/fifty-fifty-icon.png',
    price_coins: 300,
    category: 'powerups',
    tags: ['powerup', 'help', 'game'],
    metadata: { powerup_type: 'fifty_fifty', uses: 1 },
  },
  {
    name: 'Tiempo Extra',
    description: '+15 segundos para responder',
    item_type: 'powerup' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/powerups/extra-time.png',
    icon_url: '/powerups/icons/extra-time-icon.png',
    price_coins: 600,
    category: 'powerups',
    tags: ['powerup', 'time', 'game'],
    metadata: { powerup_type: 'extra_time', seconds_added: 15 },
  },

  // TITLES
  {
    name: 'Novato',
    description: 'Título: "El Novato"',
    item_type: 'title' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/titles/novice.png',
    icon_url: '/titles/icons/novice-icon.png',
    price_coins: 100,
    category: 'titles',
    tags: ['title', 'beginner'],
    metadata: { title_text: 'El Novato', color: '#808080' },
  },
  {
    name: 'Maestro',
    description: 'Título: "Maestro del Quiz"',
    item_type: 'title' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/titles/master.png',
    icon_url: '/titles/icons/master-icon.png',
    price_coins: 5000,
    price_gems: 50,
    category: 'titles',
    tags: ['title', 'master'],
    required_level: 25,
    metadata: { title_text: 'Maestro del Quiz', color: '#9b59b6' },
  },
  {
    name: 'Leyenda',
    description: 'Título: "Leyenda Viviente"',
    item_type: 'title' as ItemType,
    rarity: 'legendary' as ItemRarity,
    image_url: '/titles/legend.png',
    icon_url: '/titles/icons/legend-icon.png',
    price_gems: 200,
    is_premium: true,
    category: 'titles',
    tags: ['title', 'legend'],
    required_level: 50,
    metadata: { title_text: 'Leyenda Viviente', color: '#FFD700' },
  },

  // MORE SKINS
  {
    name: 'Piel Robot',
    description: 'Piel metálica futurista',
    item_type: 'skin' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/items/skins/skin-robot.png',
    icon_url: '/items/skins/icons/skin-robot-icon.png',
    price_coins: 2000,
    category: 'avatar',
    tags: ['skin', 'robot', 'futuristic'],
    required_level: 12,
  },
  {
    name: 'Piel Zombie',
    description: 'Piel de no-muerto',
    item_type: 'skin' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/items/skins/skin-zombie.png',
    icon_url: '/items/skins/icons/skin-zombie-icon.png',
    price_coins: 800,
    category: 'avatar',
    tags: ['skin', 'zombie', 'halloween'],
    required_level: 8,
  },
  {
    name: 'Piel Cristal',
    description: 'Piel transparente de cristal',
    item_type: 'skin' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/items/skins/skin-crystal.png',
    icon_url: '/items/skins/icons/skin-crystal-icon.png',
    price_gems: 80,
    is_premium: true,
    category: 'avatar',
    tags: ['skin', 'crystal', 'transparent'],
    required_level: 20,
  },

  // MORE ACCESSORIES
  {
    name: 'Capa de Héroe',
    description: 'Capa roja de superhéroe',
    item_type: 'accessory' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/items/accessories/hero-cape.png',
    icon_url: '/items/accessories/icons/hero-cape-icon.png',
    price_coins: 1200,
    category: 'accessories',
    tags: ['accessory', 'cape', 'hero'],
    required_level: 15,
  },
  {
    name: 'Alas de Ángel',
    description: 'Alas blancas celestiales',
    item_type: 'accessory' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/items/accessories/angel-wings.png',
    icon_url: '/items/accessories/icons/angel-wings-icon.png',
    price_coins: 4000,
    price_gems: 40,
    category: 'accessories',
    tags: ['accessory', 'wings', 'angel'],
    required_level: 25,
  },
  {
    name: 'Auriculares Gaming',
    description: 'Auriculares con LED RGB',
    item_type: 'accessory' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/items/accessories/headphones.png',
    icon_url: '/items/accessories/icons/headphones-icon.png',
    price_coins: 600,
    category: 'accessories',
    tags: ['accessory', 'headphones', 'gaming'],
    required_level: 5,
  },
  {
    name: 'Bufanda Invernal',
    description: 'Bufanda cálida para el invierno',
    item_type: 'accessory' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/items/accessories/scarf.png',
    icon_url: '/items/accessories/icons/scarf-icon.png',
    price_coins: 350,
    category: 'accessories',
    tags: ['accessory', 'scarf', 'winter'],
    required_level: 1,
  },
  {
    name: 'Máscara de Ninja',
    description: 'Máscara negra sigilosa',
    item_type: 'accessory' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/items/accessories/ninja-mask.png',
    icon_url: '/items/accessories/icons/ninja-mask-icon.png',
    price_coins: 1500,
    category: 'accessories',
    tags: ['accessory', 'mask', 'ninja'],
    required_level: 10,
  },

  // MORE FRAMES
  {
    name: 'Marco Neón',
    description: 'Marco con efecto neón',
    item_type: 'badge' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/frames/neon-frame.png',
    icon_url: '/frames/icons/neon-icon.png',
    price_coins: 2000,
    category: 'frames',
    tags: ['frame', 'neon', 'glow'],
    required_level: 12,
  },
  {
    name: 'Marco Diamante',
    description: 'Marco de diamante brillante',
    item_type: 'badge' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/frames/diamond-frame.png',
    icon_url: '/frames/icons/diamond-icon.png',
    price_gems: 150,
    is_premium: true,
    category: 'frames',
    tags: ['frame', 'diamond', 'premium'],
    required_level: 30,
  },

  // MORE EMOTES
  {
    name: 'Emoji Enojado',
    description: 'Emoticono de enojo',
    item_type: 'emote' as ItemType,
    rarity: 'common' as ItemRarity,
    image_url: '/emotes/angry.png',
    icon_url: '/emotes/icons/angry-icon.png',
    price_coins: 200,
    category: 'emotes',
    tags: ['emote', 'emotion', 'angry'],
    required_level: 1,
  },
  {
    name: 'Emoji LOL',
    description: 'Risa extrema',
    item_type: 'emote' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/emotes/lol.png',
    icon_url: '/emotes/icons/lol-icon.png',
    price_coins: 400,
    category: 'emotes',
    tags: ['emote', 'emotion', 'lol'],
    required_level: 3,
  },
  {
    name: 'Emoji Estrella',
    description: 'Emoticono con estrellas en los ojos',
    item_type: 'emote' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/emotes/star-eyes.png',
    icon_url: '/emotes/icons/star-eyes-icon.png',
    price_coins: 800,
    category: 'emotes',
    tags: ['emote', 'emotion', 'stars'],
    required_level: 10,
  },

  // MORE BOOSTS
  {
    name: 'Boost Precisión',
    description: 'Aumenta precisión por 1 hora',
    item_type: 'boost' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/boosts/accuracy-boost.png',
    icon_url: '/boosts/icons/accuracy-boost-icon.png',
    price_gems: 15,
    category: 'boosts',
    tags: ['boost', 'accuracy', 'temporary'],
    metadata: { duration_minutes: 60, multiplier: 1.5, boost_type: 'accuracy' },
  },
  {
    name: 'Boost Velocidad',
    description: 'Responde más rápido por 30 min',
    item_type: 'boost' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/boosts/speed-boost.png',
    icon_url: '/boosts/icons/speed-boost-icon.png',
    price_coins: 800,
    category: 'boosts',
    tags: ['boost', 'speed', 'temporary'],
    metadata: { duration_minutes: 30, bonus_time: 5, boost_type: 'speed' },
  },

  // MORE POWERUPS
  {
    name: 'Bomba de Conocimiento',
    description: 'Revela la respuesta correcta',
    item_type: 'powerup' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/powerups/knowledge-bomb.png',
    icon_url: '/powerups/icons/knowledge-bomb-icon.png',
    price_gems: 20,
    category: 'powerups',
    tags: ['powerup', 'reveal', 'game'],
    metadata: { powerup_type: 'reveal_answer', uses: 1 },
  },
  {
    name: 'Duplicador de Puntos',
    description: 'Duplica puntos de la siguiente pregunta',
    item_type: 'powerup' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/powerups/point-doubler.png',
    icon_url: '/powerups/icons/point-doubler-icon.png',
    price_coins: 700,
    category: 'powerups',
    tags: ['powerup', 'points', 'game'],
    metadata: { powerup_type: 'double_points', uses: 1 },
  },

  // MORE TITLES
  {
    name: 'Cerebrito',
    description: 'Título: "El Cerebrito"',
    item_type: 'title' as ItemType,
    rarity: 'uncommon' as ItemRarity,
    image_url: '/titles/brain.png',
    icon_url: '/titles/icons/brain-icon.png',
    price_coins: 500,
    category: 'titles',
    tags: ['title', 'smart'],
    required_level: 5,
    metadata: { title_text: 'El Cerebrito', color: '#3498db' },
  },
  {
    name: 'Veloz',
    description: 'Título: "Relámpago"',
    item_type: 'title' as ItemType,
    rarity: 'rare' as ItemRarity,
    image_url: '/titles/lightning.png',
    icon_url: '/titles/icons/lightning-icon.png',
    price_coins: 1500,
    category: 'titles',
    tags: ['title', 'speed'],
    required_level: 15,
    metadata: { title_text: 'Relámpago', color: '#f39c12' },
  },
  {
    name: 'Invencible',
    description: 'Título: "El Invencible"',
    item_type: 'title' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/titles/invincible.png',
    icon_url: '/titles/icons/invincible-icon.png',
    price_gems: 100,
    category: 'titles',
    tags: ['title', 'power'],
    required_level: 35,
    metadata: { title_text: 'El Invencible', color: '#e74c3c' },
  },

  // LIMITED EDITION ITEMS
  {
    name: 'Skin Halloween',
    description: 'Skin especial de Halloween',
    item_type: 'skin' as ItemType,
    rarity: 'legendary' as ItemRarity,
    image_url: '/items/skins/skin-halloween.png',
    icon_url: '/items/skins/icons/skin-halloween-icon.png',
    price_gems: 250,
    is_premium: true,
    is_limited_edition: true,
    stock_limit: 500,
    current_stock: 500,
    category: 'avatar',
    tags: ['skin', 'halloween', 'limited'],
    required_level: 20,
  },
  {
    name: 'Marco Navideño',
    description: 'Marco especial de Navidad',
    item_type: 'badge' as ItemType,
    rarity: 'epic' as ItemRarity,
    image_url: '/frames/christmas-frame.png',
    icon_url: '/frames/icons/christmas-icon.png',
    price_coins: 3000,
    is_limited_edition: true,
    stock_limit: 1000,
    current_stock: 1000,
    category: 'frames',
    tags: ['frame', 'christmas', 'limited'],
    required_level: 10,
  },
];

async function seedShopItems() {
  console.log('🌱 Seeding shop items...');

  for (const item of shopItems) {
    try {
      // Check if item exists
      const existing = await prisma.shop_items.findFirst({
        where: { name: item.name },
      });

      if (existing) {
        await prisma.shop_items.update({
          where: { item_id: existing.item_id },
          data: item,
        });
        console.log(`✅ Updated: ${item.name} (${item.rarity})`);
      } else {
        await prisma.shop_items.create({
          data: item,
        });
        console.log(`✅ Created: ${item.name} (${item.rarity})`);
      }
    } catch (error) {
      console.error(`❌ Error with ${item.name}:`, error);
    }
  }

  console.log('✨ Shop items seeding completed!');
  console.log(`📊 Total items: ${shopItems.length}`);
}

// Run seed
seedShopItems()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

